# GitOps deployment manifest for production
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: risk-engine-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rothschild/risk-engine.git
    targetRevision: main
    path: infra/helm
    helm:
      valueFiles:
        - values/production/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: risk-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - .spec.template.spec.containers[].image