computeTier: gpu-optimized
cuda:
  enabled: true
  version: "12.4"
nodeSelector:
  cloud.google.com/gke-accelerator: nvidia-tesla-t4
tolerations:
- key: nvidia.com/gpu
  operator: Exists
  effect: NoSchedule

  autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: nvidia.com/gpu
        target:
          type: Utilization
          averageUtilization: 80